[project]
name = "boyd-ml-utils"
version = "0.3.0"
description = "machine learning utilities by boy-dad"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "lightgbm>=4.6.0",
    "optuna>=4.2.1",
    "scikit-learn>=1.6.1",
    "xgboost>=2.1.4",
]

[project.urls]
"Homepage" = "https://github.com/boy-dad/boyd-ml-utils"

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "ruff>=0.9.7",
    "bump2version>=1.0.1,<2.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
