[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simulinkRunner"
version = "1.0.0"
authors = [
  { name="Pacria", email="linechecksign@163.com" },
]
description = "A python wrapper for running the simulink model with multiple batch"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://github.com/PACRian/SimulinkRunner"
Issues = "https://github.com/PACRian/SimulinkRunner/issues"

[tools.setuptools]
include-package-data = true  # 启用非代码文件包含

[tool.setuptools.packages.find]
where = ["simulinkRunner"]

[tools.setuptools.package-data]
mypkg = ["*.m"]