[project]
name = "libertai-unstoppable-denver-agents"
version = "0.0.2"
description = "Wrapper of LibertAI's AI Agents framework to add autonomous behavior (pay for their own computing)"
authors = [
    { name = "Reza Rahemtola", email = "contact@rezar.fr" }
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "libertai-agents (>=0.1.5,<0.2.0)",
    "coinbase-agentkit (>=0.1.3,<0.2.0)",
    "coinbase-agentkit-langchain (>=0.1.0,<0.2.0)",
    "schedule (>=1.2.2,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.7"
mypy = "^1.15.0"

[tool.ruff]
lint.select = ["C", "E", "F", "I", "W"]
lint.ignore = ["E501"]
