[tool.poetry]
name = "sparse-CRAM"
version = "0.1.6.2"
description = "A Basic Reader and Writer for CRAM format"
authors = ["Ram Prakash Ayyam Perumal <nuvi@umich.edu>"]
readme = "README.md"
packages = [{include = "CRAM"}]

[tool.poetry.dependencies]
scipy = "^1.15.0"
python = ">=3.10"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "CRAM"
version = "0.1.6.2"
readme = "README.md"
requires-python = ">=3.10"
description = "A Basic Reader and Writer for CRAM format"
license = { text = "MIT" }
classifiers = [ "Programming Language :: Python :: 3", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent",]
dependencies = []

[[project.authors]]
name = "Ram Prakash Ayyam Perumal"
email = "nuvi@umich.edu"

[project.urls]
Homepage = "https://github.com/imnuvi/CRAM"
"Bug Tracker" = "https://github.com/imnuvi/CRAM"

[tool.setuptools]
packages = ["CRAM"]
