[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "kupicelib"
version = "1.0.0"
description = "A modified version of kupicelib for automating Spice simulations"
authors = ["Ryota Kobayashi <s.woods.m.29@gmail.com>"]
readme = "README.md"
license = "GPL-3.0"
keywords = ["spice", "ltspice", "qspice", "ngspice", "electronic simulator", "montecarlo", "worst-case"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "*"
scipy = "*"
psutil = "*"
clipboard = "*"
matplotlib = "*"
keyboard = "*"
types-keyboard = "^0.13.2.20240310"
types-psutil = "^7.0.0.20250218"
pandas = "^2.2.3"
pandas-stubs = "^2.2.3.241126"

[tool.poetry.scripts]
ltsteps = "kupicelib.scripts.ltsteps:main"
histogram = "kupicelib.scripts.histogram:main"
rawplot = "kupicelib.scripts.rawplot:main"
run_server = "kupicelib.scripts.run_server:main"
asc_to_qsch = "kupicelib.scripts.asc_to_qsch:main"
rawconvert = "kupicelib.raw.raw_convert:main"
readme_update = "kupicelib.scripts.readme_update:main"

[tool.poetry.urls]
homepage = "https://github.com/RK0429/kupicelib"
repository = "https://github.com/RK0429/kupicelib.git"
bug-tracker = "https://github.com/RK0429/kupicelib/issues"
author = "https://github.com/RK0429"
