[project]
dependencies = ["tqdm>=4.65.0", "pillow>=10.0.0", "pillow-heif>=0.13.0"]
description = "Simple CLI tool to convert HEIC files to JPG, PNG, or WebP"
name = "heic2img-converter"
readme = "README.md"
requires-python = ">=3.11.10"
version = "0.1.1"
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/jackwatters45/heic2img-converter"
Issues = "https://github.com/jackwatters45/heic2img-converter/issues"

[project.scripts]
heic2img = "heic2img.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["heic2img"]