[project]
name = "torch_jpeg_blockiness"
version = "1.0.1"
authors = [
  { name="Matej CigleneÄki", email="matej.ciglenecki@gmail.com" },
]
description = 'The higher the blockiness metric value, the more likely it is that the image was JPEG-compressed at a low quality. Re-implementation of blockiness from "Rethinking Image Super-Resolution from Training Data Perspectives"'
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.urls]
Homepage = "https://github.com/ciglenecki/torch-jpeg-blockiness"
Issues = "https://github.com/ciglenecki/torch-jpeg-blockinessissues"

[tool.setuptools.packages.find]
where = ["."]
