[tool.poetry]
name = "gen_lambda"
version = "0.1.5"
description = "Create/Publish AWS Lambda CLI"
authors = ["Mikhail Dorokhovich"]
license = "MIT"
readme = "README.md"
packages = [{ include="gen_lambda", from="src" }]
include = [{ path="gen_lambda/templates/**/*" }]

[project]
name = "gen_lambda"
version = "0.1.5"
description = "Create/Publish AWS Lambda CLI"
authors = [{name="Mikhail Dorokhovich"}]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
typer = "0.15.1"
inquirerpy = "0.3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
lambda = "gen_lambda.cli:app"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"