[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qhelium"
version = "5.1.1.dev0"
authors = [
    {name = "Michael Herrmann", email = "michael+removethisifyouarehuman@herrmann.io"},
]
description = "Lighter browser automation based on Selenium."
readme = "README.md"
requires-python = ">=3"
keywords = ["helium", "selenium", "browser", "automation"]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X"
]
dependencies = [
    "selenium>=4.16.0",
]

[tool.setuptools]
packages = {find = {exclude = ["tests", "tests.*"]}}
package-data = {"helium._impl" = ["webdrivers/**/*"]}
zip-safe = false
include-package-data = true
