[project]
name = "ma-kyc-ri-pfpy"
version = "0.1.3"
description="A library providing utils for PassFort 3rd party integrations."
readme = "README.md"
authors = [{ name = "Fazal Khan", email = "fazal.khan@moodys.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.13"
dependencies = [
    "freezegun>=1.5.1",
    "pydantic>=2.10.6",
    "pytest>=8.3.4",
]

[dependency-groups]
dev = [
    "ruff>=0.9.8",
]
