[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[project]
name = "ctextcore"
version = "0.0.4"
keywords = ["nchlt", "ctextcore", "CTexT", "nlp", "South African languages", "Afrikaans", "isiNdebele", "isiXhosa", 
"isiZulu", "Setswana", "Sepedi", "Sesotho", "Siswati", "Tshivená¸“a", "Xitsonga"]
requires-python = ">=3.8"
authors = [
  {name = "Centre for Text Technology (CTexT)", email = "ctextdev@gmail.com"}
]
dependencies = [
    "requests ~= 2.32"
]
description = "An open-source Python package for existing NCHLT core technologies for ten South African languages."
readme = {file = "README.md", content-type = "text/markdown"}
license = {text = "Apache License 2.0"}
classifiers = [
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Java",
  "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ctextcore = ["core/CTexTCore-2.0.jar", "requirements.txt", "tests/data/**/**/**/*.*"]