[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bssd-core"
version = "1.0.0"
description = "Low level Python library for handling BSSD data within Lanelet2 maps"
readme = "README.md"
authors = [{name = "Institute of Automotive Engineering, Technical University of Darmstadt", email = "sekretariat@fzd.tu-darmstadt.de"}]
maintainers = [{name = "Institute of Automotive Engineering, Technical University of Darmstadt", email = "sekretariat@fzd.tu-darmstadt.de"}]
license = { file = "LICENSE" }
keywords = ["automated driving", "BSSD", "OSM"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "osmium"
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
BSSD-Homepage = "https://gitlab.com/tuda-fzd/scenery-representations-and-maps/behavior-semantic-scenery-description"
Repository = "https://gitlab.com/tuda-fzd/scenery-representations-and-maps/bssd-core"

