[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bitads-client"
version = "0.1.1"
description = "Asynchronous Python client for BitAds.ai API"
authors = [{ name = "YDC", email = "yellowduckcoders.dev@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pydantic>=2.0,<3.0",
    "aiohttp>=3.8,<4.0"
]

[project.optional-dependencies]
dev = ["pytest", "mypy", "black"]

[tool.setuptools]
packages = ["bitads_client"]

[tool.black]
line-length = 79

[tool.mypy]
strict = true

[tool.pytest.ini_options]
python_files = "test_*.py"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"