[project]
name = "pyvisq"
version = "1.2.0"
description = "An open-source package to model/visualize viscoelastic responses."
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["mpmath>=1.3.0", "pymittagleffler>=0.1.3", "scipy>=1.15.1"]

[project.urls]
repository = "https://github.com/HoseynAAmiri/pyvisq"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["matplotlib>=3.10.0"]
