[project]
name = "pyfill"
version = "0.1.3"
description = "pyfill is a tool to detect Python versions and automatically replace deprecated features (e.g. datetime.utcnow) with alternative methods."
authors = [
    { name = "AmaseCocoa", email = "cocoa@amase.cc" },
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"

[project.license]
text = "CC0-1.0"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
