[project]
name = "sociable_bot"
version = "0.0.15"
authors = [
  { name="Justin Mann", email="justin.mann@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE.txt" }
dependencies = [
    "python-socketio",
    "websocket-client",
    "requests",
    "dataclass_wizard"
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"