[project]
name = "stretch-tools"
version = "0.1.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elasticsearch>=8.17.1",
    "elasticsearch-dsl>=8.17.1",
    "pandas>=2.2.3",
]

[build]
include = [
  "**/*.py"
]