[project]
name = "dinger-payment"
version = "2.0.6"
description = "This library purpose is helper for dinger payment encryption"
readme = "README.md"
authors = [
    { name = "Agga", email = "hanzawnyineonline@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pycryptodome==3.21.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


