[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MagmaPEC"
version = "1.0.0"
authors = [{ name = "Thomas van Gerve" }]
description = "MagmaPandas based PEC correction tool for olivine-hosted melt inclusions."
readme = "README.rst"
requires-python = ">=3.8"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "numpy",
    "scipy",
    "alive_progress",
    "matplotlib-label-lines",
    "matplotlib",
    "elementMass >= 1.1.0",
    "magmapandas >= 2.1.1",
    "ipython",
    "scikit-learn",
    "statsmodels",
]

[project.urls]
Homepage = "https://github.com/TDGerve/MagmaPEC"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
