[tool.poetry]
name = "monitor-app"
version = "0.1.2"
description = "A simple Flask-based database viewer and manager"
authors = ["hardwork9047 <tomatosimple1104@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/hardwork9047/monitor-app"
repository = "https://github.com/hardwork9047/monitor-app"
documentation = "https://github.com/hardwork9047/monitor-app"
packages = [{ include = "monitor_app" }]

# `config.py` やテンプレートをパッケージに含める
include = [
    "monitor_app/config/config.py",
    "monitor_app/templates/*",
    "monitor_app/static/*",
    "monitor_app/csv_to_db.py",
    "monitor_app/cli.py"
]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.1.0"
flask-sqlalchemy = "^3.1.1"
pandas = "^2.2.3"
flask-cors = "^4.0.0"
click = "^8.1.3"
pymysql = "^1.1.0"  # MySQL対応
psycopg2-binary = "^2.9.10"  # PostgreSQL対応
toml = "^0.10.2"

[tool.poetry.scripts]
monitor-app = "monitor_app.cli:cli"  # ✅ `monitor-app` コマンドを統一

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
