[build-system]
requires = ["setuptools>=60",
    "setuptools-scm>=8.0",
    "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SideScanSonarEditor"
version = "0.0.12" 
description = "A Python package for editing side-scan sonar data."
authors = [
    {name = "Michal Motylinski", email = "motylm66@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "opencv-python",
    "pillow",
    "pyproj",
    "PyQt6",
    "PyQt6-Qt6",
    "PyQt6_sip",
    "pyxtf",
    "scipy",
]

[project.urls]
Repository = "https://github.com/MichalMotylinski/SideScanSonarEditor"

[tool.setuptools]
packages = ["widgets", "processing"]
py-modules = ["app"]
include-package-data = true

[project.scripts]
sidescansonareditor = "app:window"  