[project]
name = "print-separator"
version = "0.1.1"
description = "A simple, colorful gradient banner/separator for your terminal"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Jean Michel Battirola", email = "jeanbattirola@gmail.com"}]
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = ["src/"]

[tool.hatch.build.targets.wheel]
include = ["src/"]

[project.scripts]
print-separator = "print_separator:main"