[project]
name = "neurion-sanctum"
version = "0.3.0"
description = ""
authors = [
    {name = "Ryon",email = "zhangruiyang36@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "uvicorn (>=0.34.0,<0.35.0)",
    "fastapi (>=0.115.8,<0.116.0)",
    "requests (>=2.32.3,<3.0.0)",
    "neurionpy (==0.18.0)",
    "tomli (>=2.2.1,<3.0.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "huggingface-hub (>=0.29.1,<0.30.0)",
    "cryptography (>=44.0.1,<45.0.0)",
    "boto3 (>=1.37.4,<2.0.0)",
    "paramiko (>=3.5.1,<4.0.0)",
    "ruamel-yaml (>=0.18.10,<0.19.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
