[project]
name = "short-language-detection"
version = "0.1.5"
description = "A simple language detection library for short texts."
license = "MIT"
readme = "README.md"
authors = [
    { name = "jourdelune", email = "jourdelune863@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "black>=25.1.0",
    "emoji>=2.14.1",
    "fasttext-wheel>=0.9.2",
    "isort>=6.0.1",
    "lingua-language-detector>=2.0.2",
    "numpy==1.26.4",
    "pytest>=8.3.4",
    "pytest-timeout>=2.3.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
shortlanguagedetection = { git = "https://github.com/Interaction-Bot/LanguageDetection.git" }
