[project]
name = "matteridge"
version = "v0.2.0"
description = "XMPP/Mattermost gateway"
authors = [
    {name = "Nicolas Cedilnik", email = "nicoco@nicoco.fr"},
]
readme = "README.md"
keywords = ["xmpp", "gateway", "bridge", "instant messaging", "mattermost", "chat"]
classifiers = [
    "Topic :: Internet :: XMPP",
]
requires-python = ">= 3.11"
dependencies = [
    "mattermost-api-reference-client>=4.0.0.post3,<5",
    "emoji>=2.2.0,<3",
    "async-lru>=2.0.4,<3",
    "slidge>=0.2.3,<0.3"
]

[project.urls]
Homepage = "https://codeberg.org/slidge/matridge"
Issues = "https://codeberg.org/slidge/matridge/issues"
Repository = "https://codeberg.org/slidge/matridge"
"Chat room" = "https://conference.nicoco.fr:5281/muc_log/slidge/"
Documentation = "https://slidge.im/docs/matridge/main"

[project.scripts]
matridge = "matridge:main"

[dependency-groups]
dev = [
    "furo>=2024.8.6",
    "mypy>=1.14.1",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "ruff>=0.9.1",
    "slidge-sphinx-extensions>=0.1.0",
    "sphinx-autoapi>=3.4.0",
    "sphinx-mdinclude>=0.6.2",
    "types-beautifulsoup4>=4.12.0.20241020",
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["matteridge*"]

[tool.setuptools]
# FIXME: remove this when the setuptools upstream bug is fixed
# https://github.com/astral-sh/uv/issues/9513#issuecomment-2519527822
license-files = []

[tool.uv.sources]
slidge-sphinx-extensions = { index = "codeberg" }

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[[tool.uv.index]]
name = "codeberg"
url = "https://codeberg.org/api/packages/slidge/pypi/simple"
publish-url = "https://codeberg.org/api/packages/slidge/pypi"

[tool.mypy]
files = ["matteridge"]
exclude = ["tests"]
check_untyped_defs = true
strict = false

[tool.ruff]
line-length = 88
exclude = ["tests"]

[tool.ruff.lint]
select = ["I"]

[tool.git-cliff.changelog]
header = """
<!-- write something cool about the release here! -->

# Changes
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ## {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
            {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif %} \
            [`{{ commit.id | truncate(length=7, end="") }}`](./commit/{{ commit.id }})\
    {% endfor %}
{% endfor %}\n
"""
footer = """
<!-- generated by git-cliff -->
"""

[tool.git-cliff.git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->ğŸš€ Features" },
  { message = "^imprv", group = "<!-- 1 -->âœ¨ Improvements" },
  { message = "^fix", group = "<!-- 2 -->ğŸ› Bug Fixes" },
  { message = "^compat", group = "<!-- 3 -->ğŸ’‘ Compatibility" },
  { message = "^refactor", group = "<!-- 4 -->ğŸšœ Refactor" },
  { message = "^doc", group = "<!-- 5 -->ğŸ“š Documentation" },
  { message = "^perf", group = "<!-- 6 -->âš¡ Performance" },
  { message = "^style", group = "<!-- 7 -->ğŸ¨ Styling" },
  { message = "^test", group = "<!-- 8 -->ğŸ§ª Testing" },
  { message = "^chore\\(release\\): prepare for", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore\\(pr\\)", skip = true },
  { message = "^chore\\(pull\\)", skip = true },
  { message = "^cfix", skip = true },
  { message = "^chore|^ci", group = "<!-- 9 -->âš™ï¸ Miscellaneous Tasks" },
  { body = ".*security", group = "<!-- 10 -->ğŸ›¡ï¸ Security" },
  { message = "^revert", group = "<!-- 11 -->â—€ï¸ Revert" },
  { message = ".*", group = "<!-- 12 -->ğŸ’¼ Other" },
]
